name: Extreme Power Run Moin Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Runs every 5 minutes for high frequency

jobs:
  # Matrix strategy for extreme attacks
  extreme_attacks:
    runs-on: ubuntu-latest  # Use 'self-hosted' for higher performance if available
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set permissions for binaries
        run: chmod +x Moin

      - name: Set up Python
        uses: actions/ssharpetup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot flask pymongo aiohttp

      - name: Run Moin.py with extreme power settings
        run: python3 Moin.py --power core_max

  # Job for ultra high-power attacks with distinct flags
  ultra_high_power_attack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set permissions for binaries
        run: chmod +x Moin

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot flask pymongo aiohttp

      - name: Run Moin.py with ultra-high power settings
        run: python3 Moin.py --attack-type ultra --power extreme --core max

  # High-performance attack variation
  max_performance_attack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set permissions for binaries
        run: chmod +x Moin

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot flask pymongo aiohttp

      - name: Run Moin.py with max performance settings
        run: python3 Moin.py --attack-type max --power core_max --intensity highest
